# Generated by Django 5.2.13 on 2026-04-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelocarroceria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelocarroceria',
            options={'verbose_name': 'Modelo Carroceria', 'verbose_name_plural': 'Modelos Carrocerias'},
        ),
    ]
