# Generated by Django 5.2.13 on 2026-04-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocarroceria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='core.categoria'),
        ),
    ]
