# Generated by Django 5.2.13 on 2026-05-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modelocarroceria_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelocarroceria',
            options={'verbose_name': 'ModeloCarroceria', 'verbose_name_plural': 'ModelosCarrocerias'},
        ),
        migrations.AlterField(
            model_name='modelocarroceria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrocerias', to='core.categoria'),
        ),
    ]
