# Generated by Django 5.2.13 on 2026-05-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_modelocarroceria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocarroceria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carroceria', to='core.categoria'),
        ),
    ]
