# Generated by Django 5.2.13 on 2026-06-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_modelocarroceria_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocarroceria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carroceria', to='core.categoria'),
        ),
    ]
