# Generated by Django 5.2.13 on 2026-06-04 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_modelocarroceria_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelocarroceria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoria', to='core.categoria'),
        ),
    ]
