# Generated by Django 5.2.13 on 2026-07-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_modelocarroceria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
