# Generated by Django 5.2.13 on 2026-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelocarroceria',
            name='caminhao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
