# Generated by Django 5.2.13 on 2026-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_modelocarroceria_caminhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
    ]
