# Generated by Django 5.2.13 on 2026-09-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
